# Generated by Django 5.2.4 on 2026-01-18 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_category', models.CharField(choices=[('Microcontrollers / Boards', 'Microcontrollers / Boards'), ('Sensors', 'Sensors'), ('Actuators', 'Actuators'), ('Electric Components', 'Electric Components'), ('Displays', 'Displays'), ('Miscellaneous', 'Miscellaneous')], max_length=30)),
                ('comp_name', models.CharField(max_length=100)),
                ('comp_quantity_available', models.IntegerField()),
                ('comp_status', models.CharField(choices=[('Defective', 'Defective'), ('Deleted', 'Deleted'), ('working', 'working')], default='working', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('del_std_roll_number', models.CharField(max_length=10, unique=True)),
                ('del_std_first_name', models.CharField(max_length=30)),
                ('del_std_last_name', models.CharField(max_length=30)),
                ('del_std_college_email', models.EmailField(max_length=254, unique=True)),
                ('del_std_deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedStudentIssueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('del_std_issue_roll_number', models.CharField(max_length=10)),
                ('del_std_issue_component_name', models.CharField(max_length=100)),
                ('del_std_issue_quantity_issued', models.PositiveIntegerField()),
                ('del_std_issue_deleted_at', models.DateField(auto_now_add=True)),
                ('del_std_issue_issue_date', models.DateField(blank=True, null=True)),
                ('del_std_issue_return_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_first_name', models.CharField(max_length=30)),
                ('std_last_name', models.CharField(max_length=30)),
                ('std_roll_number', models.CharField(max_length=10, unique=True)),
                ('std_college_email', models.EmailField(max_length=254, unique=True)),
                ('std_password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StudentIssueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_issue_quantity_issued', models.PositiveIntegerField()),
                ('std_issue_form_date', models.DateField(blank=True, null=True)),
                ('std_issue_issue_date', models.DateField(blank=True, null=True)),
                ('std_issue_return_date', models.DateField(blank=True, null=True)),
                ('status_from_student', models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Issued', 'Issued'), ('Returned', 'Returned'), ('Rejectedbyteacher', 'Rejectedbyteacher')], max_length=20, null=True)),
                ('status_from_teacher', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending', max_length=20)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp_issue_logs', to='final.component')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_issue_logs', to='final.student')),
            ],
        ),
    ]
