# Generated by Django 5.2.4 on 2026-01-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('comp_cate_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_cate_slug', models.CharField(max_length=20, unique=True)),
                ('comp_cate_category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StatusChoices',
            fields=[
                ('status_ch_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_ch_status_label', models.CharField(max_length=20)),
            ],
        ),
    ]
