# Generated by Django 5.2.4 on 2026-01-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentissuelog',
            old_name='status_from_student',
            new_name='std_issue_status_from_student',
        ),
        migrations.RenameField(
            model_name='studentissuelog',
            old_name='status_from_teacher',
            new_name='std_issue_status_from_teacher',
        ),
    ]
