# Generated by Django 5.2.4 on 2026-01-22 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_first_name', models.CharField(max_length=30)),
                ('std_last_name', models.CharField(max_length=30)),
                ('std_roll_number', models.CharField(max_length=10, unique=True)),
                ('std_college_email', models.EmailField(max_length=254, unique=True)),
                ('std_phone_number', models.CharField(max_length=10, null=True, unique=True)),
                ('std_password', models.CharField(max_length=128)),
                ('std_year_of_passing', models.PositiveSmallIntegerField()),
                ('std_is_active', models.BooleanField(default=True)),
                ('std_joined_at', models.DateField(auto_now_add=True)),
                ('std_deactivated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=100)),
                ('comp_quantity_available', models.PositiveIntegerField(default=0)),
                ('comp_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ComponentCategory_fkey', to='final.componentcategory')),
                ('comp_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='StatusChoices_fkey', to='final.statuschoices')),
            ],
        ),
        migrations.CreateModel(
            name='StudentIssueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_issue_quantity_issued', models.PositiveIntegerField()),
                ('std_issue_form_date', models.DateField(blank=True, null=True)),
                ('std_issue_issue_date', models.DateField(blank=True, null=True)),
                ('std_issue_return_date', models.DateField(blank=True, null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp_issue_logs', to='final.component')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_issue_logs', to='final.student')),
            ],
        ),
    ]
