# Generated by Django 5.2.4 on 2026-01-22 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_student_component_studentissuelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='comp_status',
        ),
        migrations.RemoveField(
            model_name='component',
            name='comp_id',
        ),
        migrations.RemoveField(
            model_name='componentcategory',
            name='comp_cate_category_id',
        ),
        migrations.RemoveField(
            model_name='componentcategory',
            name='comp_cate_slug',
        ),
        migrations.AddField(
            model_name='component',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='componentcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='component',
            name='comp_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentcategory_fkey', to='final.componentcategory'),
        ),
        migrations.DeleteModel(
            name='StatusChoices',
        ),
    ]
