# Generated by Django 5.2.4 on 2026-01-22 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_remove_component_comp_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentissuelog',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comp_issue_logs', to='final.component'),
        ),
    ]
