# Generated by Django 5.2.4 on 2026-01-26 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0004_alter_studentissuelog_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches_branch_name', models.CharField(max_length=30)),
                ('branches_branch_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='std_college_email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Use your official college email', regex='^[bB][2-5][0-9]{5}@skit\\.ac\\.in$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only letters allowed (2–30 characters)', regex='^[A-Za-z]{2,30}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only letters allowed (2–30 characters)', regex='^[A-Za-z]{2,30}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_phone_number',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian mobile number', regex='^[6-9][0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_roll_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Roll number must be exactly 10 digits', regex='^[2-5][0-9][a-zA-Z]{5}[0-9]{3}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_year_of_passing',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('std_roll_number__regex', '^[2-5][0-9][a-zA-Z]{5}[0-9]{3}$')), name='roll_number_10_digits'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('std_phone_number__regex', '^[6-9][0-9]{9}$')), name='phone_number_india'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('std_college_email__regex', '^[bB][2-5][0-9]{5}@skit\\.ac\\.in$')), name='college_email_domain'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('std_first_name', models.F('std_last_name')), _negated=True), name='first_last_name_not_same'),
        ),
    ]
