# Generated by Django 5.2.4 on 2026-01-26 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_branches_alter_student_std_college_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_branch',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='branch_name', to='final.branches'),
        ),
        migrations.AddField(
            model_name='student',
            name='std_year',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th')], db_index=True, default=2),
        ),
    ]
