# Generated by Django 5.2.4 on 2026-01-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0006_student_std_branch_student_std_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='comp_popularity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='component',
            name='comp_status',
            field=models.BooleanField(default=True),
        ),
    ]
