# Generated by Django 5.2.4 on 2026-01-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0007_component_comp_popularity_component_comp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='branches_rollno_code',
            field=models.CharField(default='CX', max_length=3),
        ),
        migrations.AlterField(
            model_name='branches',
            name='branches_branch_code',
            field=models.CharField(max_length=3),
        ),
    ]
