# Generated by Django 5.2.4 on 2025-10-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0009_alter_studentissuelog_status_from_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentissuelog',
            name='studentid',
        ),
    ]
