# Generated by Django 5.2.4 on 2025-10-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_component_componentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('Microcontroller', 'Microcontroller/Board'), ('Sensors', 'Sensors'), ('Actuator', 'Actuator'), ('Electronic', 'Electronic Component'), ('Display', 'Display'), ('Misc', 'Miscellaneous')], max_length=20),
        ),
    ]
