# Generated by Django 5.2.4 on 2025-10-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_component_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('Microcontrollers / Boards', 'Microcontrollers / Boards'), ('Sensors', 'Sensors'), ('Actuators', 'Actuators'), ('Electric Components', 'Electric Components'), ('Displays', 'Displays'), ('Miscellaneous', 'Miscellaneous')], max_length=30),
        ),
    ]
