"""
Django settings for teststudy project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

# to parse the connection string and auto separate hosts,pasword,dbname etc
import dj_database_url

from pathlib import Path

#for using env varaibles
from dotenv import load_dotenv

#ye runtime pe load hoga iliye error ide mein dega
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables from .env
load_dotenv(BASE_DIR / "config" / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

#ye bhi use kar sakte
# SECRET_KEY = os.environ.get('SECRET_KEY')

SECRET_KEY = config('SECRET_KEY')
ADMIN_PATH = os.getenv("ADMIN_PATH", "admin/")
# SECURITY WARNING: don't run with debug turned on in production!

# Django rejects all hosts not in ALLOWED_HOSTS                       (by CHATGPT)
# If you forget to add your Render domain → 400 Bad Request
DEBUG = config('DEBUG', cast=bool,default=True)



# ✔ avoids empty strings
# ✔ works in all environments
# ✔ no crash if env is missing

#ye likh sakte if empty string ho  gai by chance
# ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",") if host.strip()]


#but apan direct likho
ALLOWED_HOSTS=os.getenv("ALLOWED_HOSTS", "").split(",")

CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "")

# Convert to list if not empty
if CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = CSRF_TRUSTED_ORIGINS.split(",")
else:
    CSRF_TRUSTED_ORIGINS = []
# note: *** DON'T ADD LOCALHOST AS ALLOWED HOSTS ON RENDER  ***



# --------------------
# Session cookies
# --------------------
SESSION_COOKIE_HTTPONLY = True            # JS cannot access the cookie
SESSION_COOKIE_SECURE = config('DEBUG', cast=bool,default=False)              # Only sent over HTTPS (enable in prod)
SESSION_COOKIE_SAMESITE = 'Lax'           # Protect against CSRF; 'Strict' is stricter
SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', 1800))        # 30 minutes idle timeout
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# --------------------
# CSRF cookie
# --------------------
CSRF_COOKIE_SECURE =config('DEBUG', cast=bool,default=False)                 # Only sent over HTTPS
CSRF_COOKIE_HTTPONLY = True              # Must be readable by JS for AJAX POSTs
CSRF_COOKIE_SAMESITE = 'Lax'              # Prevent CSRF via cross-site requests

# --------------------
# HTTPS / proxy settings
# --------------------
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Behind Render or other proxies
SECURE_SSL_REDIRECT = not DEBUG             # Force all requests to HTTPS

# --------------------
# Security headers
# --------------------
SECURE_BROWSER_XSS_FILTER = True       # Enable browser XSS filtering
SECURE_CONTENT_TYPE_NOSNIFF = True     # Prevent MIME type sniffing
X_FRAME_OPTIONS = 'DENY'               # Prevent clickjacking



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # these we added new (Local apps)
     'final.apps.FinalConfig',

]

# 'whitenoise.middleware.WhiteNoiseMiddleware',
# to serve static files from statiscroot  on render

# ****  ORDER OF MIDDLEWARE MATTERS   ****
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'teststudy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # BASE_DIR / 'templates',
            'final/templates',

        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'teststudy.wsgi.application'

LOGIN_URL = '/login/'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASE_URL = os.environ.get('DATABASE_URL')
if not DATABASE_URL:
    raise ValueError("DATABASE_URL environment variable not set")

DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
}


#used at start
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

#These are where your static files live before collectstatic
STATICFILES_DIRS = [
    # BASE_DIR / 'static',
    'final/static',
                    ]

#for PRODUCTION (as given by CHATGPT)
STATIC_ROOT = BASE_DIR / 'staticfilesforproduction'

#after adding whitenoise to serve static files from static root on render
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
